name: Natural Green Dot Factory

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Random Commit Logic
        run: |
          # สุ่มรอเพื่อความเนียน
          sleep $(( ( RANDOM % 60 )  + 1 ))
          
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # ดึงข้อมูลล่าสุดมาก่อนป้องกันการขัดกัน
          git pull origin main

          ITERATIONS=$(( ( RANDOM % 4 )  + 1 ))
          for i in $(seq 1 $ITERATIONS)
          do
            echo "Snake food added at $(date)" >> daily_report.txt
            git add daily_report.txt
            git commit -m "Natural Commit #$i: $(date)"
          done

      - name: Push changes
        run: git push origin main --force
